# Generated by Django 3.2.25 on 2025-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('A', 'Burnout-Yogini'), ('B', 'Ashtanga-Warrior'), ('C', 'Homeoffice-Yogi'), ('D', 'Casual-Stretcher')], max_length=1)),
            ],
        ),
    ]
