# Generated by Django 3.2.25 on 2025-04-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='duration',
        ),
    ]
