# Generated by Django 4.2.13 on 2025-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_main_character", models.BooleanField(default=False)),
                ("is_antagonist", models.BooleanField(default=False)),
            ],
        ),
    ]
