# Generated by Django 4.2.13 on 2025-02-12 19:22

from django.db import migrations

def create_initial_characters(apps, schema_editor):
    Character = apps.get_model('app', 'Character')

    main_characters = [
        {"name": "Aragorn", "is_main_character": True},
        {"name": "Legolas", "is_main_character": True},
        {"name": "Gimli", "is_main_character": True},
        {"name": "Gandalf", "is_main_character": True},
        {"name": "Frodo", "is_main_character": True},
    ]

    antagonists = [
        {"name": "Sauron", "is_antagonist": True},
        {"name": "Saruman", "is_antagonist": True},
        {"name": "Nazgûl", "is_antagonist": True},
        {"name": "Lurtz", "is_antagonist": True},
        {"name": "Gollum", "is_antagonist": True},
    ]

    for character in main_characters:
        Character.objects.create(**character)

    for character in antagonists:
        Character.objects.create(**character)

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_character"),
    ]

    operations = [
        migrations.RunPython(create_initial_characters),
    ]
