# Generated by Django 3.2.25 on 2025-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250507_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='yoga_type',
            field=models.CharField(choices=[('Burnout-Yogini', 'Burnout-Yogini'), ('Ashtanga-Warrior', 'Ashtanga-Warrior'), ('Homeoffice-Yogini', 'Homeoffice-Yogini'), ('Casual-Stretcher', 'Casual-Stretcher')], default='Burnout-Yogini', max_length=50),
        ),
    ]
