# Generated by Django 3.2.25 on 2025-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_yogaclass_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogaclass',
            old_name='description',
            new_name='ideal_for',
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='type',
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='class_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='yoga_type',
            field=models.CharField(choices=[('Burnout-Yogini', 'Burnout-Yogini'), ('Ashtanga-Warrior', 'Ashtanga-Warrior'), ('Homeoffice-Yogi', 'Homeoffice-Yogi'), ('Casual-Stretcher', 'Casual-Stretcher'), ('Cross-Type', 'Cross-Type')], default='Burnout-Yogini', max_length=50),
        ),
    ]
