# Generated by Django 3.2.25 on 2025-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250429_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='ideal_for_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
