# Generated by Django 3.2.25 on 2025-05-22 11:37

from django.db import migrations


def update_yoga_types(apps, schema_editor):
    YogaClass = apps.get_model('app', 'YogaClass')
    YogaClass.objects.filter(yoga_type='Homeoffice-Yogi').update(yoga_type='Homeoffice-Yogini')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_yogaclass_yoga_type'),
    ]

    operations = [
        migrations.RunPython(update_yoga_types),
    ]
