# Generated by Django 4.2.13 on 2025-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_auto_20250212_1922"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="attack_points",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="life_points",
            field=models.IntegerField(default=100),
        ),
    ]
