# Generated by Django 3.2.25 on 2025-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_update_homeoffice_yoga_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
