# Generated by Django 4.2.13 on 2025-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_character_attack_points_character_life_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="attack_points",
            new_name="attacks",
        ),
        migrations.AddField(
            model_name="character",
            name="defense",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="character",
            name="quotes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="character",
            name="race",
            field=models.CharField(default="Human", max_length=100),
        ),
        migrations.AddField(
            model_name="character",
            name="secret_weapon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="special_ability",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
