# Generated by Django 3.2.25 on 2025-02-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_attack_points_character_attacks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artifact_name', models.CharField(max_length=100)),
                ('offensive_property', models.IntegerField(default=0)),
                ('defensive_property', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='app.character')),
            ],
        )
    ]
