# Generated by Django 3.2.25 on 2025-05-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ollamaresponse_questionnaireresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='user_id',
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questionnaireresult',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
