# Generated by Django 3.2.25 on 2025-02-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250222_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleoutcome',
            name='main_artifact',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='battle_main', 
                to='app.Artifact'),
        ),
        migrations.AddField(
            model_name='battleoutcome',
            name='opponent_artifact',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='battle_opponent', 
                to='app.Artifact'),
        ),
        migrations.AlterModelTable(
            name='artifact',
            table='app_artifacts',
        ),
    ]
