# Generated by Django 3.2.25 on 2025-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250531_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollamaresponse',
            name='combinations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
