# Generated by Django 3.2.25 on 2025-02-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250223_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='secret_weapon',
        ),
    ]
