# Generated by Django 3.2.25 on 2025-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_battleoutcome_coin_toss_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleoutcome',
            name='outcome',
            field=models.CharField(max_length=255),
        ),
    ]
