# Generated by Django 3.2.25 on 2025-03-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_battleoutcome_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleoutcome',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='battleoutcome',
            name='player',
        ),
        migrations.AddField(
            model_name='battleoutcome',
            name='opponent_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_opponent', to='app.character'),
        ),
        migrations.AddField(
            model_name='battleoutcome',
            name='player_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_player', to='app.character'),
        ),
    ]
