name: Django Prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]  # Remove 3.13 as it's not stable yet

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django  # Add explicit Django installation
        pip install requests
        pip install mysqlclient django
        pip install -r requirements.txt
        pip install playwright
        playwright install --with-deps chromium
    - name: Run Tests
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
        MAILCHIMP_LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
        MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
      run: |
        python3 manage.py test
