name: Django and Vue.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Install Python dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        playwright install --with-deps chromium

    # Set up Node.js for Vue.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use a stable Node.js version

    # Install frontend dependencies
    - name: Install Frontend Dependencies
      working-directory: static/webpack
      run: |
        npm install

    # Build the Vue.js frontend
    - name: Build Frontend
      working-directory: static/webpack
      run: |
        npm run build

    # Collect Django static files
    - name: Collect Static Files
      env:
        DJANGO_SETTINGS_MODULE: yogi.settings
      run: |
        python3 manage.py collectstatic --noinput

    # Run Django tests
    - name: Run Tests
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
        MAILCHIMP_LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
        MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
      run: |
        python3 manage.py test
